

pipeline{
    agent any

    stages{
        stage('Test stage') {
            steps{
                echo 'This is TEST stage'
                bat 'mvn clean test'
            }
        }
    }
    post{
        success{
            echo 'Test succeed!'
            script {
                // Cucumber Report
                cucumber fileIncludePattern: '**/*.json'
            }
        }
        failure {
            echo 'Test failed!'
        }
    }
}